### ISSUE TITLE
Evaluate new lint-test library

### ISSUE THREAD

**Issue by a11n** [a11n/lint-junit-rule#1]
https://android.googlesource.com/platform/tools/base/+/4065f99c18aec7bc9519b74f00ebc6dfb22920f1

**Comment by a11n** [comment]
https://android.googlesource.com/platform/tools/base/+/studio-1.3-release/lint/libs/lint-tests/build.gradle

**Comment by a11n** [comment]
It's released now:
https://bintray.com/android/android-tools/com.android.tools.lint.lint-tests/view

**Comment by MichaelEvans** [comment]
@a11n have you tried the library? there's no documentation yet it seems.

**Comment by a11n** [comment]
Hi @MichaelEvans,

yes, I've evaluate the library. The first version unfortunately contained a dependency issue [1] which got fixed by version 24.3.0. The current version has a class loader issue [2], which should now be fixed in version 24.3.1 (but I haven't tested this yet).

I documented all my findings in my Android Lint reference guide [3], which is like an unofficial documentation ;-) You can find an example in my custom Lint rule template project [4].

Hope that helps you.
1. https://code.google.com/p/android/issues/detail?id=175161
2. https://code.google.com/p/android/issues/detail?id=182195
3. https://github.com/a11n/android-lint/tree/master/5_testing
4. https://github.com/a11n/CustomLintRules/blob/master/src/test/java/de/ad/android/tools/lint/HelloWorldDetectorTest.java

**Comment by a11n** [comment]
The official test support is now incorporated into this rule.
