### ISSUE TITLE
Could not resolve v0.3.0

### ISSUE THREAD

**Issue by shiraji** [a11n/lint-junit-rule#14]
In our project, it's fail to resolve this library from jcenter

Here is the gradle script

``` groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$GRADLE_PLUGIN_VERSION"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$KOTLIN_PLUGIN_VERSION"
        classpath "com.neenbedankt.gradle.plugins:android-apt:$APT_PLUGIN_VERSION"
        classpath "com.novoda:bintray-release:$BINTRAY_PLUGIN_VERSION"
        classpath "com.netflix.nebula:gradle-extra-configurations-plugin:$CONFIG_PLUGIN_VERSION"
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
```

``` groovy
apply plugin: 'java'

targetCompatibility = JavaVersion.VERSION_1_7
sourceCompatibility = JavaVersion.VERSION_1_7

configurations {
    lintChecks
}

dependencies {
    compile "com.android.tools.lint:lint-api:$LINT_VERSION"
    compile "com.android.tools.lint:lint-checks:$LINT_VERSION"

    testCompile "junit:junit:$JUNIT_VERSION"
    testCompile "com.android.tools.lint:lint:$LINT_VERSION"
    testCompile "com.android.tools.lint:lint-tests:$LINT_VERSION"
    testCompile "com.android.tools:testutils:$LINT_VERSION"

    testCompile "de.ad:lint-junit-rule:0.3.0"
    testCompile 'de.ad:lint-assertj:0.3.0'
    testCompile 'de.ad:lint-hamcrest:0.3.0'

    lintChecks files(jar)
}

jar {
    manifest {
        attributes("Lint-Registry": "permissions.dispatcher.PermissionDispatcherIssueRegistry")
    }
}
```

Error message

```
* What went wrong:
Could not resolve all dependencies for configuration ':lint:testCompile'.
> Could not find de.ad:lint-junit-rule:0.3.0.
  Searched in the following locations:
      https://jcenter.bintray.com/de/ad/lint-junit-rule/0.3.0/lint-junit-rule-0.3.0.pom
      https://jcenter.bintray.com/de/ad/lint-junit-rule/0.3.0/lint-junit-rule-0.3.0.jar
  Required by:
      PermissionsDispatcher:lint:unspecified
> Could not find de.ad:lint-assertj:0.3.0.
  Searched in the following locations:
      https://jcenter.bintray.com/de/ad/lint-assertj/0.3.0/lint-assertj-0.3.0.pom
      https://jcenter.bintray.com/de/ad/lint-assertj/0.3.0/lint-assertj-0.3.0.jar
  Required by:
      PermissionsDispatcher:lint:unspecified
> Could not find de.ad:lint-hamcrest:0.3.0.
  Searched in the following locations:
      https://jcenter.bintray.com/de/ad/lint-hamcrest/0.3.0/lint-hamcrest-0.3.0.pom
      https://jcenter.bintray.com/de/ad/lint-hamcrest/0.3.0/lint-hamcrest-0.3.0.jar
  Required by:
      PermissionsDispatcher:lint:unspecified
```

There seems no jars in jcenter. Check this https://jcenter.bintray.com/de/ad/

Could you upload jar file? or am I missing something?

Thanks in advance.

**Comment by a11n** [comment]
Many thanks for reporting this! I'm sorry for the inconvenience.

Unfortunately I messed something up when requesting to add this lib to jCenter's central repository. I somehow configured a wrong group ID :-(

So it's available via jcenter but under this link (I'll check how to convert this do a Gradle dependency):
https://jcenter.bintray.com/lint-junit-rule/

In the sample [1] you'll find the current work around by adding my user repo to the `repositories` closure:

``` groovy
  maven {
    url 'https://dl.bintray.com/a11n/maven/'
  }
```

...but I understand that this is not an elegant solution. You can use it in order to integrate the library in your project while I'm working on the jcenter issue.
1. https://github.com/a11n/lint-junit-rule/blob/master/sample/build.gradle

**Comment by shiraji** [comment]
Thanks for your help. Let me know it is available from jcenter.

**Comment by a11n** [comment]
I contacted JCenter support. I will keep you updated.

**Comment by shiraji** [comment]
Thanks for update! I am waiting to see that at jcenter!

**Comment by a11n** [comment]
Thanks to Bintray support, the library is now available at http://jcenter.bintray.com/de/ad/lint-junit-rule/

Could you confirm it's working for you?

**Comment by shiraji** [comment]
Thanks! 

I confirmed for `de.ad:lint-junit-rule:0.3.0`. But `de.ad:lint-assertj:0.3.0` and `de.ad:lint-hamcrest:0.3.0` are not working for me.

**Comment by a11n** [comment]
Thank you very much for your confirmation.

Re-linking of the other packages is in progress... waiting for response from support team.

**Comment by a11n** [comment]
It should work now: http://jcenter.bintray.com/de/ad/

**Comment by shiraji** [comment]
I confirmed that. Thanks a lot!
